In [ ]:
import pandas as pd
from pathlib import Path

# Anchor to repo root by finding a known marker file (CLAUDE.md)
ROOT = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / "CLAUDE.md").exists())
pbp_dir = ROOT / "data/raw/pbp"
raw_files = list(pbp_dir.glob("*.parquet"))

print(f"CWD: {Path.cwd()}")
print(f"Looking in: {pbp_dir}  ->  {len(raw_files)} files")

# Fallback: if none found, locate parquet files anywhere under the repo
if not raw_files:
    raw_files = list(ROOT.glob("**/*.parquet"))
    print("Fallback found:", [str(f.relative_to(ROOT)) for f in raw_files[:5]])

df = pd.concat([pd.read_parquet(f) for f in raw_files], ignore_index=True)
print(f"{len(raw_files)} games | {df.shape[0]:,} rows | {df.shape[1]} cols")
df.head(20)

CWD: d:\Python Projects\NBA Free Throw Rule Change\notebooks
Looking in: d:\Python Projects\NBA Free Throw Rule Change\data\raw\pbp  ->  20 files
20 games | 10,767 rows | 24 cols

,gameId,actionNumber,clock,period,teamId,teamTricode,personId,playerName,playerNameI,xLegacy,...,scoreHome,scoreAway,pointsTotal,location,description,actionType,subType,videoAvailable,shotValue,actionId
0,0022500001,2,PT12M00.00S,1,0,,0,,,0,...,0,0,0,,Start of 1st Period (7:44 PM EST),period,start,1,0,1
1,0022500001,4,PT12M00.00S,1,1610612760,OKC,1631096,Holmgren,C. Holmgren,0,...,,,0,h,Jump Ball Holmgren vs. Adams: Tip to Thompson,Jump Ball,,1,0,2
2,0022500001,8,PT11M36.00S,1,1610612745,HOU,1630578,Sengun,A. Sengun,-179,...,,,0,v,MISS Sengun 25' 3PT Jump Shot,Missed Shot,Jump Shot,1,3,3
3,0022500001,9,PT11M31.00S,1,1610612760,OKC,1641717,Wallace,C. Wallace,0,...,,,0,h,Wallace REBOUND (Off:0 Def:1),Rebound,Unknown,1,0,4
4,0022500001,10,PT11M26.00S,1,1610612760,OKC,1631096,Holmgren,C. Holmgren,0,...,2,0,2,h,Holmgren 1' Cutting Layup Shot (2 PTS) (Dort 1...,Made Shot,Cutting Layup Shot,1,2,5
5,0022500001,12,PT11M26.00S,1,1610612745,HOU,1631095,Smith Jr.,J. Smith Jr.,0,...,,,0,v,Smith Jr. S.FOUL (P1.T1) (E.Dalen),Foul,Shooting,1,0,6
6,0022500001,14,PT11M26.00S,1,1610612760,OKC,1631096,Holmgren,C. Holmgren,0,...,3,0,3,h,Holmgren Free Throw 1 of 1 (3 PTS),Free Throw,Free Throw 1 of 1,1,0,7
7,0022500001,15,PT11M08.00S,1,1610612745,HOU,1641708,Thompson,A. Thompson,233,...,,,0,v,MISS Thompson 3PT Jump Shot,Missed Shot,Jump Shot,1,3,8
8,0022500001,16,PT11M04.00S,1,1610612745,HOU,1631095,Smith Jr.,J. Smith Jr.,0,...,,,0,v,Smith Jr. REBOUND (Off:1 Def:0),Rebound,Unknown,1,0,9
9,0022500001,17,PT11M02.00S,1,1610612745,HOU,1631095,Smith Jr.,J. Smith Jr.,-7,...,3,2,5,v,Smith Jr. 1' Putback Layup (2 PTS),Made Shot,Putback Layup Shot,1,2,10
10,0022500001,18,PT10M50.00S,1,1610612760,OKC,1631096,Holmgren,C. Holmgren,64,...,5,2,7,h,Holmgren 7' Floating Jump Shot (5 PTS) (Wallac...,Made Shot,Floating Jump shot,1,2,11
11,0022500001,20,PT10M40.00S,1,1610612760,OKC,1631096,Holmgren,C. Holmgren,0,...,,,0,h,Holmgren Violation:Kicked Ball (Z.Zarba),Violation,Kicked Ball,0,0,12
12,0022500001,21,PT10M24.00S,1,1610612745,HOU,1630578,Sengun,A. Sengun,72,...,,,0,v,MISS Sengun 15' Pullup Jump Shot,Missed Shot,Pullup Jump shot,1,2,13
13,0022500001,23,PT10M24.00S,1,0,,1610612745,,,0,...,,,0,v,Rockets Rebound,Rebound,Unknown,0,0,14
14,0022500001,24,PT10M24.00S,1,0,,1610612745,,,0,...,,,0,v,Rockets Turnover: Shot Clock (T#1),Turnover,Shot Clock Turnover,1,0,15
15,0022500001,25,PT10M11.00S,1,1610612760,OKC,1628983,Gilgeous-Alexander,S. Gilgeous-Alexander,0,...,,,0,h,Gilgeous-Alexander Bad Pass Turnover (P1.T1),Turnover,Bad Pass,1,0,16
16,0022500001,25,PT10M11.00S,1,1610612745,HOU,1630578,Sengun,A. Sengun,0,...,,,0,v,Sengun STEAL (1 STL),,,1,0,17
17,0022500001,27,PT10M07.00S,1,1610612745,HOU,201142,Durant,K. Durant,0,...,5,4,9,v,Durant Running Dunk (2 PTS) (Thompson 1 AST),Made Shot,Running Dunk Shot,1,2,18
18,0022500001,29,PT09M52.00S,1,1610612760,OKC,1631096,Holmgren,C. Holmgren,59,...,7,4,11,h,Holmgren 13' Turnaround Fadeaway (7 PTS),Made Shot,Turnaround Fadeaway shot,1,2,19
19,0022500001,30,PT09M35.00S,1,1610612745,HOU,1631095,Smith Jr.,J. Smith Jr.,164,...,7,7,14,v,Smith Jr. 26' 3PT Jump Shot (5 PTS) (Thompson ...,Made Shot,Jump Shot,1,3,20
20,0022500001,32,PT09M21.00S,1,1610612760,OKC,1641717,Wallace,C. Wallace,74,...,,,0,h,MISS Wallace 26' 3PT Jump Shot,Missed Shot,Jump Shot,1,3,21
21,0022500001,33,PT09M17.00S,1,1610612745,HOU,1630578,Sengun,A. Sengun,0,...,,,0,v,Sengun REBOUND (Off:0 Def:1),Rebound,Unknown,1,0,22
22,0022500001,34,PT09M06.00S,1,1610612745,HOU,201142,Durant,K. Durant,85,...,,,0,v,MISS Durant 9' Pullup Jump Shot,Missed Shot,Pullup Jump shot,1,2,23
23,0022500001,35,PT09M04.00S,1,1610612760,OKC,1631096,Holmgren,C. Holmgren,0,...,,,0,h,Holmgren REBOUND (Off:0 Def:1),Rebound,Unknown,1,0,24
24,0022500001,36,PT08M57.00S,1,1610612760,OKC,1628983,Gilgeous-Alexander,S. Gilgeous-Alexander,-217,...,,,0,h,MISS Gilgeous-Alexander 25' 3PT Step Back Jump...,Missed Shot,Step Back Jump shot,1,3,25
25,0022500001,37,PT08M54.00S,1,1610612760,OKC,1628392,Hartenstein,I. Hartenstein,0,...,,,0,h,Hartenstein REBOUND (Off:1 Def:0),Rebound,Unknown,1,0,26
26,0022500001,38,PT08M49.00S,1,1610612760,OKC,1629652,Dort,L. Dort,-10,...,9,7,16,h,Dort 1' Driving Dunk (2 PTS),Made Shot,Driving Dunk Shot,1,2,27
27,0022500001,39,PT08M20.00S,1,1610612745,HOU,1641708,Thompson,A. Thompson,227,...,,,0,v,MISS Thompson 3PT Jump Shot,Missed Shot,Jump Shot,1,3,28
28,0022500001,40,PT08M18.00S,1,1610612745,HOU,203500,Adams,S. Adams,0,...,,,0,v,Adams REBOUND (Off:1 Def:0),Rebound,Unknown,1,0,29
29,0022500001,41,PT08M17.00S,1,1610612745,HOU,1641708,Thompson,A. Thompson,5,...,9,9,18,v,Thompson 4' Pullup Jump Shot (2 PTS) (Adams 1 ...,Made Shot,Pullup Jump shot,1,2,30
30,0022500001,43,PT08M17.00S,1,1610612760,OKC,1641717,Wallace,C. Wallace,0,...,,,0,h,Wallace S.FOUL (P1.T1) (Z.Zarba),Foul,Shooting,1,0,31
31,0022500001,45,PT08M17.00S,1,1610612745,HOU,1641708,Thompson,A. Thompson,0,...,9,10,19,v,Thompson Free Throw 1 of 1 (3 PTS),Free Throw,Free Throw 1 of 1,1,0,32
32,0022500001,46,PT08M07.00S,1,1610612760,OKC,1631096,Holmgren,C. Holmgren,0,...,,,0,h,Holmgren Lost Ball Turnover (P1.T2),Turnover,Lost Ball,1,0,33
33,0022500001,46,PT08M07.00S,1,1610612745,HOU,1630578,Sengun,A. Sengun,0,...,,,0,v,Sengun STEAL (2 STL),,,1,0,34
34,0022500001,48,PT08M03.00S,1,1610612745,HOU,1631095,Smith Jr.,J. Smith Jr.,168,...,,,0,v,MISS Smith Jr. 26' 3PT Running Pull-Up Jump Shot,Missed Shot,Running Pull-Up Jump Shot,1,3,35
35,0022500001,49,PT08M00.00S,1,1610612760,OKC,1628392,Hartenstein,I. Hartenstein,0,...,,,0,h,Hartenstein REBOUND (Off:1 Def:1),Rebound,Unknown,1,0,36
36,0022500001,50,PT07M49.00S,1,1610612760,OKC,1628392,Hartenstein,I. Hartenstein,9,...,,,0,h,MISS Hartenstein 12' Driving Floating Jump Shot,Missed Shot,Driving Floating Jump Shot,1,2,37
37,0022500001,51,PT07M47.00S,1,1610612760,OKC,1628392,Hartenstein,I. Hartenstein,0,...,,,0,h,Hartenstein REBOUND (Off:2 Def:1),Rebound,Unknown,1,0,38
38,0022500001,52,PT07M45.00S,1,1610612760,OKC,1628392,Hartenstein,I. Hartenstein,-76,...,,,0,h,MISS Hartenstein 8' Jump Shot,Missed Shot,Jump Shot,1,2,39
39,0022500001,53,PT07M44.00S,1,0,,1610612760,,,0,...,,,0,h,THUNDER Rebound,Rebound,Unknown,0,0,40

In [9]:
df[df["actionType"] == "Free Throw"].head(40)   # eyeball the FT text format

,gameId,actionNumber,clock,period,teamId,teamTricode,personId,playerName,playerNameI,xLegacy,...,scoreHome,scoreAway,pointsTotal,location,description,actionType,subType,videoAvailable,shotValue,actionId
6,0022500001,14,PT11M26.00S,1,1610612760,OKC,1631096,Holmgren,C. Holmgren,0,...,3,0,3,h,Holmgren Free Throw 1 of 1 (3 PTS),Free Throw,Free Throw 1 of 1,1,0,7
31,0022500001,45,PT08M17.00S,1,1610612745,HOU,1641708,Thompson,A. Thompson,0,...,9,10,19,v,Thompson Free Throw 1 of 1 (3 PTS),Free Throw,Free Throw 1 of 1,1,0,32
47,0022500001,66,PT06M40.00S,1,1610612760,OKC,1631096,Holmgren,C. Holmgren,0,...,14,14,28,h,Holmgren Free Throw 1 of 2 (12 PTS),Free Throw,Free Throw 1 of 2,1,0,48
49,0022500001,69,PT06M40.00S,1,1610612760,OKC,1631096,Holmgren,C. Holmgren,0,...,15,14,29,h,Holmgren Free Throw 2 of 2 (13 PTS),Free Throw,Free Throw 2 of 2,1,0,50
52,0022500001,73,PT06M29.00S,1,1610612745,HOU,1641708,Thompson,A. Thompson,0,...,15,17,32,v,Thompson Free Throw 1 of 1 (8 PTS),Free Throw,Free Throw 1 of 1,1,0,53
63,0022500001,91,PT05M15.00S,1,1610612760,OKC,1629652,Dort,L. Dort,0,...,18,21,39,h,Dort Free Throw 1 of 2 (3 PTS),Free Throw,Free Throw 1 of 2,1,0,64
64,0022500001,92,PT05M15.00S,1,1610612760,OKC,1629652,Dort,L. Dort,0,...,19,21,40,h,Dort Free Throw 2 of 2 (4 PTS),Free Throw,Free Throw 2 of 2,1,0,65
74,0022500001,106,PT04M03.00S,1,1610612745,HOU,201142,Durant,K. Durant,0,...,23,22,45,v,Durant Free Throw 1 of 2 (5 PTS),Free Throw,Free Throw 1 of 2,1,0,75
76,0022500001,109,PT04M03.00S,1,1610612745,HOU,201142,Durant,K. Durant,0,...,23,23,46,v,Durant Free Throw 2 of 2 (6 PTS),Free Throw,Free Throw 2 of 2,1,0,77
83,0022500001,125,PT03M26.00S,1,1610612760,OKC,1628983,Gilgeous-Alexander,S. Gilgeous-Alexander,0,...,24,23,47,h,Gilgeous-Alexander Free Throw 1 of 2 (3 PTS),Free Throw,Free Throw 1 of 2,1,0,84
86,0022500001,126,PT03M26.00S,1,1610612760,OKC,1628983,Gilgeous-Alexander,S. Gilgeous-Alexander,0,...,,,0,h,MISS Gilgeous-Alexander Free Throw 2 of 2,Free Throw,Free Throw 2 of 2,1,0,87
129,0022500001,199,PT11M09.00S,2,1610612760,OKC,1631096,Holmgren,C. Holmgren,0,...,30,30,60,h,Holmgren Free Throw 1 of 1 (16 PTS),Free Throw,Free Throw 1 of 1,1,0,130
150,0022500001,228,PT08M11.00S,2,1610612745,HOU,1629006,Okogie,J. Okogie,0,...,39,40,79,v,Okogie Free Throw 1 of 2 (4 PTS),Free Throw,Free Throw 1 of 2,1,0,151
155,0022500001,237,PT08M11.00S,2,1610612745,HOU,1629006,Okogie,J. Okogie,0,...,39,41,80,v,Okogie Free Throw 2 of 2 (5 PTS),Free Throw,Free Throw 2 of 2,1,0,156
167,0022500001,253,PT06M35.00S,2,1610612745,HOU,203500,Adams,S. Adams,0,...,42,45,87,v,Adams Free Throw 1 of 2 (1 PTS),Free Throw,Free Throw 1 of 2,1,0,168
168,0022500001,254,PT06M35.00S,2,1610612745,HOU,203500,Adams,S. Adams,0,...,42,46,88,v,Adams Free Throw 2 of 2 (2 PTS),Free Throw,Free Throw 2 of 2,1,0,169
236,0022500001,342,PT00M05.10S,2,1610612745,HOU,1630578,Sengun,A. Sengun,0,...,47,56,103,v,Sengun Free Throw 1 of 2 (9 PTS),Free Throw,Free Throw 1 of 2,1,0,237
239,0022500001,347,PT00M05.10S,2,1610612745,HOU,1630578,Sengun,A. Sengun,0,...,47,57,104,v,Sengun Free Throw 2 of 2 (10 PTS),Free Throw,Free Throw 2 of 2,1,0,240
245,0022500001,356,PT00M00.70S,2,1610612760,OKC,1642349,Mitchell,A. Mitchell,0,...,51,57,108,h,Mitchell Free Throw 1 of 1 (12 PTS),Free Throw,Free Throw 1 of 1,1,0,246
278,0022500001,403,PT07M57.00S,3,1610612745,HOU,1630578,Sengun,A. Sengun,0,...,57,64,121,v,Sengun Free Throw 1 of 2 (11 PTS),Free Throw,Free Throw 1 of 2,1,0,279
280,0022500001,406,PT07M57.00S,3,1610612745,HOU,1630578,Sengun,A. Sengun,0,...,57,65,122,v,Sengun Free Throw 2 of 2 (12 PTS),Free Throw,Free Throw 2 of 2,1,0,281
300,0022500001,436,PT06M13.00S,3,1610612760,OKC,1641717,Wallace,C. Wallace,0,...,,,0,h,MISS Wallace Free Throw 1 of 2,Free Throw,Free Throw 1 of 2,1,0,301
305,0022500001,444,PT06M13.00S,3,1610612760,OKC,1641717,Wallace,C. Wallace,0,...,61,67,128,h,Wallace Free Throw 2 of 2 (4 PTS),Free Throw,Free Throw 2 of 2,1,0,306
326,0022500001,467,PT04M19.00S,3,1610612745,HOU,203991,Capela,C. Capela,0,...,65,70,135,v,Capela Free Throw 1 of 2 (3 PTS),Free Throw,Free Throw 1 of 2,1,0,327
327,0022500001,468,PT04M19.00S,3,1610612745,HOU,203991,Capela,C. Capela,0,...,65,71,136,v,Capela Free Throw 2 of 2 (4 PTS),Free Throw,Free Throw 2 of 2,1,0,328
355,0022500001,506,PT01M18.00S,3,1610612745,HOU,201142,Durant,K. Durant,0,...,73,77,150,v,Durant Free Throw 1 of 1 (17 PTS),Free Throw,Free Throw 1 of 1,1,0,356
361,0022500001,515,PT00M43.80S,3,1610612745,HOU,1630578,Sengun,A. Sengun,0,...,75,78,153,v,Sengun Free Throw 1 of 2 (18 PTS),Free Throw,Free Throw 1 of 2,1,0,362
364,0022500001,520,PT00M43.80S,3,1610612745,HOU,1630578,Sengun,A. Sengun,0,...,75,79,154,v,Sengun Free Throw 2 of 2 (19 PTS),Free Throw,Free Throw 2 of 2,1,0,365
395,0022500001,574,PT08M10.00S,4,1610612760,OKC,1628392,Hartenstein,I. Hartenstein,0,...,84,87,171,h,Hartenstein Free Throw 1 of 2 (3 PTS),Free Throw,Free Throw 1 of 2,1,0,396
397,0022500001,577,PT08M10.00S,4,1610612760,OKC,1628392,Hartenstein,I. Hartenstein,0,...,85,87,172,h,Hartenstein Free Throw 2 of 2 (4 PTS),Free Throw,Free Throw 2 of 2,1,0,398
405,0022500001,589,PT07M29.00S,4,1610612745,HOU,1630578,Sengun,A. Sengun,0,...,85,90,175,v,Sengun Free Throw 1 of 1 (28 PTS),Free Throw,Free Throw 1 of 1,1,0,406
413,0022500001,602,PT06M49.00S,4,1610612745,HOU,1629006,Okogie,J. Okogie,0,...,,,0,v,MISS Okogie Free Throw 1 of 2,Free Throw,Free Throw 1 of 2,1,0,414
415,0022500001,604,PT06M49.00S,4,1610612745,HOU,1629006,Okogie,J. Okogie,0,...,85,91,176,v,Okogie Free Throw 2 of 2 (6 PTS),Free Throw,Free Throw 2 of 2,1,0,416
427,0022500001,618,PT04M55.00S,4,1610612760,OKC,1628983,Gilgeous-Alexander,S. Gilgeous-Alexander,0,...,88,93,181,h,Gilgeous-Alexander Free Throw 1 of 2 (14 PTS),Free Throw,Free Throw 1 of 2,1,0,428
429,0022500001,622,PT04M55.00S,4,1610612760,OKC,1628983,Gilgeous-Alexander,S. Gilgeous-Alexander,0,...,89,93,182,h,Gilgeous-Alexander Free Throw 2 of 2 (15 PTS),Free Throw,Free Throw 2 of 2,1,0,430
436,0022500001,632,PT03M52.00S,4,1610612760,OKC,1628983,Gilgeous-Alexander,S. Gilgeous-Alexander,0,...,92,97,189,h,Gilgeous-Alexander Free Throw 1 of 2 (18 PTS),Free Throw,Free Throw 1 of 2,1,0,437
438,0022500001,635,PT03M52.00S,4,1610612760,OKC,1628983,Gilgeous-Alexander,S. Gilgeous-Alexander,0,...,93,97,190,h,Gilgeous-Alexander Free Throw 2 of 2 (19 PTS),Free Throw,Free Throw 2 of 2,0,0,439
467,0022500001,674,PT00M09.50S,4,1610612745,HOU,201142,Durant,K. Durant,0,...,,,0,v,MISS Durant Free Throw 1 of 2,Free Throw,Free Throw 1 of 2,1,0,468
472,0022500001,682,PT00M09.50S,4,1610612745,HOU,201142,Durant,K. Durant,0,...,102,104,206,v,Durant Free Throw 2 of 2 (20 PTS),Free Throw,Free Throw 2 of 2,1,0,473
503,0022500001,730,PT02M30.00S,5,1610612745,HOU,1642263,Sheppard,R. Sheppard,0,...,112,107,219,v,Sheppard Free Throw 1 of 2 (9 PTS),Free Throw,Free Throw 1 of 2,1,0,504

In [8]:
df[df['personId'] == 1631096].head(40)

,gameId,actionNumber,clock,period,teamId,teamTricode,personId,playerName,playerNameI,xLegacy,...,scoreHome,scoreAway,pointsTotal,location,description,actionType,subType,videoAvailable,shotValue,actionId
1,0022500001,4,PT12M00.00S,1,1610612760,OKC,1631096,Holmgren,C. Holmgren,0,...,,,0,h,Jump Ball Holmgren vs. Adams: Tip to Thompson,Jump Ball,,1,0,2
4,0022500001,10,PT11M26.00S,1,1610612760,OKC,1631096,Holmgren,C. Holmgren,0,...,2,0,2,h,Holmgren 1' Cutting Layup Shot (2 PTS) (Dort 1...,Made Shot,Cutting Layup Shot,1,2,5
6,0022500001,14,PT11M26.00S,1,1610612760,OKC,1631096,Holmgren,C. Holmgren,0,...,3,0,3,h,Holmgren Free Throw 1 of 1 (3 PTS),Free Throw,Free Throw 1 of 1,1,0,7
10,0022500001,18,PT10M50.00S,1,1610612760,OKC,1631096,Holmgren,C. Holmgren,64,...,5,2,7,h,Holmgren 7' Floating Jump Shot (5 PTS) (Wallac...,Made Shot,Floating Jump shot,1,2,11
11,0022500001,20,PT10M40.00S,1,1610612760,OKC,1631096,Holmgren,C. Holmgren,0,...,,,0,h,Holmgren Violation:Kicked Ball (Z.Zarba),Violation,Kicked Ball,0,0,12
18,0022500001,29,PT09M52.00S,1,1610612760,OKC,1631096,Holmgren,C. Holmgren,59,...,7,4,11,h,Holmgren 13' Turnaround Fadeaway (7 PTS),Made Shot,Turnaround Fadeaway shot,1,2,19
23,0022500001,35,PT09M04.00S,1,1610612760,OKC,1631096,Holmgren,C. Holmgren,0,...,,,0,h,Holmgren REBOUND (Off:0 Def:1),Rebound,Unknown,1,0,24
32,0022500001,46,PT08M07.00S,1,1610612760,OKC,1631096,Holmgren,C. Holmgren,0,...,,,0,h,Holmgren Lost Ball Turnover (P1.T2),Turnover,Lost Ball,1,0,33
40,0022500001,55,PT07M42.00S,1,1610612760,OKC,1631096,Holmgren,C. Holmgren,211,...,11,10,21,h,Holmgren 23' Jump Shot (9 PTS) (Dort 2 AST),Made Shot,Jump Shot,1,2,41
42,0022500001,58,PT07M10.00S,1,1610612760,OKC,1631096,Holmgren,C. Holmgren,-4,...,13,12,25,h,Holmgren 14' Jump Shot (11 PTS) (Gilgeous-Alex...,Made Shot,Jump Shot,1,2,43
47,0022500001,66,PT06M40.00S,1,1610612760,OKC,1631096,Holmgren,C. Holmgren,0,...,14,14,28,h,Holmgren Free Throw 1 of 2 (12 PTS),Free Throw,Free Throw 1 of 2,1,0,48
49,0022500001,69,PT06M40.00S,1,1610612760,OKC,1631096,Holmgren,C. Holmgren,0,...,15,14,29,h,Holmgren Free Throw 2 of 2 (13 PTS),Free Throw,Free Throw 2 of 2,1,0,50
84,0022500001,156,PT03M26.00S,1,1610612760,OKC,1631096,Holmgren,C. Holmgren,0,...,,,0,h,SUB: Caruso FOR Holmgren,Substitution,,0,0,85
123,0022500001,191,PT11M40.00S,2,1610612760,OKC,1631096,Holmgren,C. Holmgren,0,...,,,0,h,Holmgren Traveling Turnover (P2.T6),Turnover,Traveling,1,0,124
126,0022500001,194,PT11M09.00S,2,1610612760,OKC,1631096,Holmgren,C. Holmgren,-7,...,29,30,59,h,Holmgren 2' Running Layup (15 PTS) (Mitchell 1...,Made Shot,Running Layup Shot,1,2,127
129,0022500001,199,PT11M09.00S,2,1610612760,OKC,1631096,Holmgren,C. Holmgren,0,...,30,30,60,h,Holmgren Free Throw 1 of 1 (16 PTS),Free Throw,Free Throw 1 of 1,1,0,130
145,0022500001,220,PT08M29.00S,2,1610612760,OKC,1631096,Holmgren,C. Holmgren,181,...,39,39,78,h,Holmgren 23' Step Back Jump Shot (18 PTS) (Mit...,Made Shot,Step Back Jump shot,1,2,146
177,0022500001,264,PT06M01.00S,2,1610612760,OKC,1631096,Holmgren,C. Holmgren,0,...,,,0,h,Holmgren REBOUND (Off:0 Def:2),Rebound,Unknown,1,0,178
178,0022500001,265,PT05M51.00S,2,1610612760,OKC,1631096,Holmgren,C. Holmgren,49,...,,,0,h,MISS Holmgren 9' Turnaround Fadeaway Shot,Missed Shot,Turnaround Fadeaway shot,1,2,179
182,0022500001,270,PT05M44.00S,2,1610612760,OKC,1631096,Holmgren,C. Holmgren,0,...,,,0,h,SUB: Wallace FOR Holmgren,Substitution,,0,0,183
218,0022500001,318,PT02M01.00S,2,1610612760,OKC,1631096,Holmgren,C. Holmgren,0,...,,,0,h,Holmgren REBOUND (Off:1 Def:2),Rebound,Unknown,1,0,219
228,0022500001,331,PT01M05.00S,2,1610612760,OKC,1631096,Holmgren,C. Holmgren,0,...,,,0,h,Holmgren REBOUND (Off:1 Def:3),Rebound,Unknown,1,0,229
231,0022500001,335,PT00M22.80S,2,1610612760,OKC,1631096,Holmgren,C. Holmgren,-225,...,,,0,h,MISS Holmgren 27' 3PT Jump Shot,Missed Shot,Jump Shot,1,3,232
235,0022500001,340,PT00M05.10S,2,1610612760,OKC,1631096,Holmgren,C. Holmgren,0,...,,,0,h,Holmgren P.FOUL (P1.PN) (Z.Zarba),Foul,Personal,1,0,236
250,0022500001,369,PT11M47.00S,3,1610612760,OKC,1631096,Holmgren,C. Holmgren,169,...,,,0,h,MISS Holmgren 26' 3PT Jump Shot,Missed Shot,Jump Shot,1,3,251
259,0022500001,379,PT10M21.00S,3,1610612760,OKC,1631096,Holmgren,C. Holmgren,0,...,,,0,h,Holmgren Out of Bounds - Bad Pass Turnover Tur...,Turnover,Out of Bounds - Bad Pass Turnover,1,0,260
290,0022500001,422,PT06M52.00S,3,1610612760,OKC,1631096,Holmgren,C. Holmgren,-61,...,,,0,h,MISS Holmgren 12' Jump Shot,Missed Shot,Jump Shot,1,2,291
304,0022500001,442,PT06M13.00S,3,1610612760,OKC,1631096,Holmgren,C. Holmgren,0,...,,,0,h,SUB: Wiggins FOR Holmgren,Substitution,,0,0,305
351,0022500001,499,PT01M38.00S,3,1610612760,OKC,1631096,Holmgren,C. Holmgren,137,...,,,0,h,MISS Holmgren 25' 3PT Jump Shot,Missed Shot,Jump Shot,1,3,352
358,0022500001,510,PT01M04.00S,3,1610612760,OKC,1631096,Holmgren,C. Holmgren,0,...,,,0,h,Holmgren REBOUND (Off:1 Def:4),Rebound,Unknown,1,0,359
360,0022500001,513,PT00M43.80S,3,1610612760,OKC,1631096,Holmgren,C. Holmgren,0,...,,,0,h,Holmgren S.FOUL (P2.PN) (J.Goldenberg),Foul,Shooting,1,0,361
387,0022500001,560,PT09M32.00S,4,1610612760,OKC,1631096,Holmgren,C. Holmgren,0,...,,,0,h,Holmgren REBOUND (Off:1 Def:5),Rebound,Unknown,1,0,388
388,0022500001,561,PT09M21.00S,4,1610612760,OKC,1631096,Holmgren,C. Holmgren,-12,...,81,84,165,h,Holmgren 1' Alley Oop Dunk (20 PTS) (Hartenste...,Made Shot,Alley Oop Dunk Shot,1,2,389
402,0022500001,583,PT07M29.00S,4,1610612760,OKC,1631096,Holmgren,C. Holmgren,0,...,,,0,h,Holmgren S.FOUL (P3.T1) (J.Goldenberg),Foul,Shooting,1,0,403
403,0022500001,585,PT07M29.00S,4,1610612760,OKC,1631096,Holmgren,C. Holmgren,0,...,,,0,h,SUB: Gilgeous-Alexander FOR Holmgren,Substitution,,0,0,404
448,0022500001,647,PT02M33.00S,4,1610612760,OKC,1631096,Holmgren,C. Holmgren,42,...,97,99,196,h,Holmgren 4' Floating Jump Shot (22 PTS) (Dort ...,Made Shot,Floating Jump shot,1,2,449
460,0022500001,665,PT00M53.10S,4,1610612760,OKC,1631096,Holmgren,C. Holmgren,0,...,,,0,h,Holmgren L.B.FOUL (P4.T4) (J.Goldenberg),Foul,Loose Ball,1,0,461
482,0022500001,700,PT05M00.00S,5,1610612760,OKC,1631096,Holmgren,C. Holmgren,0,...,,,0,h,Jump Ball Holmgren vs. Adams: Tip to Smith Jr.,Jump Ball,,1,0,483
490,0022500001,712,PT04M15.00S,5,1610612760,OKC,1631096,Holmgren,C. Holmgren,-224,...,107,104,211,h,Holmgren 3PT Jump Shot (25 PTS) (Dort 5 AST),Made Shot,Jump Shot,1,3,491
511,0022500001,739,PT01M25.00S,5,1610612760,OKC,1631096,Holmgren,C. Holmgren,0,...,,,0,h,Holmgren S.FOUL (P5.T3) (Z.Zarba),Foul,Shooting,1,0,512